### ISSUE TITLE
Is there any downsize to convert GPR to DNG?

### ISSUE THREAD

**Issue by stephane-archer** [gopro/gpr#29]

**Comment by dnewman-gpsw** [comment]
There is no quality or information lost in the conversion, however the DNG file will be between 3-5X larger than the GPR.

**Comment by stephane-archer** [comment]
It's because DNG contain jpeg preview and the way the raw data is compress? Is it correct? Any way to convert DNG to GPR?

**Comment by dnewman-gpsw** [comment]
GPR is a DNG file, will a new type of compression (SMPTE VC5), so a GPR can also contain a JPEG thumbnail (unfortunately GoPro doesn't that.)  The reason not to add a JPEG, is that GPR are wavelet compressed, wavelets have a thumbnail inherent in the compression.  The problem is tools like LightRoom don't use this ability, instead it will decode the entire image for gallery images.  Yes you can convert most DNGs to GPRs.

**Comment by stephane-archer** [comment]
Thank you David for your great answers 🙏
What is wavelet compression? Do you mean you can decompress half of the
data and get a half resolution raw file?

**Comment by dnewman-gpsw** [comment]
Yes. You can decompress part of the data to get a lower resolution image.  A wavelet is a mathematical impulse function, these can be used for image compression without dividing the images into blocks (a quality advantage), most image compression systems use DCT (Discrete Cosine Transforms, and divide the image into blocks.)  VC5/GPR is based on CineForm compression, you can see a demo of wavelet compression on the CineForm pages https://gopro.github.io/cineform-sdk/
